/**
 * Navigation api
 * Navigation api that haleps to navigate between miniapps
 *
 * 
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * Do not edit the class manually.
 */
import {expect} from 'chai';
import NavigationRequests  from '../../src/api/NavigationRequests';

describe('NavigationApi', function(){
  let requests;
  beforeEach(function() {
    requests = new NavigationRequests({
        registerHandler(){
        },
        sendRequest(){
        }
    });

  });


    describe('navigate', function() {
      it('should send request navigate successfully', ()=> {
        //uncomment below and update the code to test navigate
        //return requests.navigate(miniAppName: string, opts: any).then(response=> {
        //  if (error) throw error;
        //  expect(response).to.be();
        //});

      });
    });

});
